In [3]:
l1=[1,2,3,4,5,6,7,8]    #one dimensional array

In [4]:
l2=[[1,2],[3,4],[5,6],[7,8]]    #two dimensional array

In [5]:
import numpy as np

In [6]:
np_arr=np.array(l2)
np_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
type(l2),type(np_arr)

(list, numpy.ndarray)

# for determine the dimension of array     ------- [arrayname.shape]

In [8]:
l1.shape

AttributeError: 'list' object has no attribute 'shape'

In [9]:
np_arr.shape

(4, 2)

# for merge of lists and convert to a numpy array

In [10]:
ls1=[1,2,3,4]
ls2=[5,6,7,8]
ls3=[9,1,2,3]
merged=np.array([ls1,ls2,ls3])
merged

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [11]:
merged.shape

(3, 4)

In [12]:
type(merged)

numpy.ndarray

# indexing of 1-dimensional and multi-dimensional array

In [13]:
ls1[0]

1

In [14]:
ls2[2]

7

In [15]:
merged[0][3]

4

In [16]:
merged[2][0]

9

# slicing of array

In [17]:
merged

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [43]:
merged[1:][0]

array([5, 6, 7, 8])

In [56]:
merged[1:,2:]

array([[7, 8],
       [2, 3]])

In [57]:
merged[2:,3:]

array([[3]])

In [67]:
n1=[1,3,5,7]
n2=[2,4,6,8]
n3=[4,2,10,3]
m=np.array([n1,n2,n3])
m

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 4,  2, 10,  3]])

In [68]:
type(m)

numpy.ndarray

In [69]:
m[2:,3:]

array([[3]])

In [70]:
m[1:,2:]

array([[ 6,  8],
       [10,  3]])

In [66]:
m[2:,0]

array([4])

In [71]:
m[0:2,0]

array([1, 2])

# mon moto array

In [72]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [73]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
np.ones((4,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])