In [1]:
import pandas as pd
import numpy as np

In [3]:
n=np.arange(0,30)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
n_reshape=n1=n.reshape(5,6)

In [5]:
n1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
n_reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# for creating DataFrame

In [7]:
df=pd.dataframe(n1,index=['R1','R2','R3','R4','R5'],coulmns=['C1','C2','C3','C4','C5','C6'])

AttributeError: module 'pandas' has no attribute 'dataframe'

In [9]:
df=pd.DataFrame(n1,index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4','C5','C6'])

In [10]:
table=df
table

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29