In [1]:
import pandas as pd
import numpy as np

In [2]:
n=np.arange(0,30)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
n_reshape=n1=n.reshape(5,6)

In [4]:
n1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
n_reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# for creating DataFrame

In [6]:
df=pd.dataframe(n1,index=['R1','R2','R3','R4','R5'],coulmns=['C1','C2','C3','C4','C5','C6'])

AttributeError: module 'pandas' has no attribute 'dataframe'

In [7]:
df=pd.DataFrame(n1,index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4','C5','C6'])

In [8]:
table=df
table

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [33]:
type(table)

pandas.core.frame.DataFrame

# Head & Tail

In [9]:
table.head(3)

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17

In [10]:
table.tail(3)

C1  C2  C3  C4  C5  C6
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [11]:
table.head(2)

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11

In [12]:
table.tail(2)

C1  C2  C3  C4  C5  C6
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [13]:
table.head()

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [14]:
table.tail()

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

# for showing the Single Row of DataFrame

In [17]:
table.loc['R3']        #using index name

C1    12
C2    13
C3    14
C4    15
C5    16
C6    17
Name: R3, dtype: int32

In [18]:
table.iloc[3]         #using index number

C1    18
C2    19
C3    20
C4    21
C5    22
C6    23
Name: R4, dtype: int32

# Slicing

In [19]:
table[1:]

C1  C2  C3  C4  C5  C6
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [20]:
table[2:]

C1  C2  C3  C4  C5  C6
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [27]:
table[:1]

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5

In [29]:
table.iloc[2:,2:]

C3  C4  C5  C6
R3  14  15  16  17
R4  20  21  22  23
R5  26  27  28  29

In [30]:
table.iloc[:3,:2]

C1  C2
R1   0   1
R2   6   7
R3  12  13

In [31]:
table[3:]

C1  C2  C3  C4  C5  C6
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

# Converting DataFrame to Array

In [32]:
table.values

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
type(table.values)

numpy.ndarray